### PR TITLE
Caching added for functions working on graphs

### PR DESCRIPTION
**Pull request by Rahgooy**
@doogrammargood I added caching for some of the functions.

### CODE REVIEW

**Comment by doogrammargood** [comment]
@Rahgooy 

In this PR, there is self.cache in ga.py and extended_graph.py, and CACHE in caching.py. Are these all necessary?

I would like to refactor some of the methods (namely Graph.maximal_independent_sets() and FUN._vertex_cost_list(g)) so that they can be cached.

I also want another constructor for ExtendedGraph to absorb the functionality of FUN.mutate_add_another_vertex.

Any thoughts?

**Comment by Rahgooy** [comment]
Ah, I forgot to commit the final changes.
In this implementation, you just add the `@wrap_with_cache` before any function related to the graph (the first parameter should be a graph, obviously all class methods of the graph are like that).
I already used cache in some of the graph class methods and also `FUN` methods `FUN._vertex_cost_list` is one of them).

I'm not sure about your last question. What do you want to do exactly?

**Comment by Rahgooy** [comment]
@doogrammargood I removed the cache related stuff from GA and extended graph. Please have a look and let me know if there are other things to fix.

**Comment by doogrammargood** [comment]
@Rahgooy 
This makes sense to me now, but I haven't run it and played around with it yet.

The two functions that I mentioned require computing the independent set and lovasz theta. It should be simple to use the decorator that you wrote to cache these quantities. I can do this later today. One thing to point out is that the output of `g.maximal_independent_sets()` is large.

**Comment by doogrammargood** [comment]
I think I should move many of the helper functions into extended_graph.py, since they compute properties of the graph.

**Pull request merged**
