### PR TITLE
Simple caching

### PR DESCRIPTION
**Pull request by Rahgooy**
I added a simple cache with `str(adjacency matrix)` as a hash function to see the hit rate of the cache.
With 10 vertices we have hit rate of 30% or so. I was looking for ways to hash a graph and came across some papers. But the problem is they try to have the same key for isomorph graphs which I remember you said is not desirable. I think if we want to use cache we need to discuss the possible hashing functions and choose those with reasonable time complexity. 

Here is one of the papers with `C` code:
[Graph isomorphism testing boosted by path coloring](https://arxiv.org/pdf/1606.00001.pdf)

### CODE REVIEW

**Comment by Rahgooy** [comment]
@doogrammargood is this okay to merge?

**Comment by doogrammargood** [comment]
@Rahgooy  Yeah go ahead and merge it. I'm a little confused about how github works. I can't checkout these changes until you merge, can I? You can just overwrite any conflicts in main.

**Comment by Rahgooy** [comment]
@doogrammargood Yes, you can. Click on "Files changed" links at the top of this page. When there are conflicts you should resolve them locally and commit before merging here.

**Comment by Rahgooy** [comment]
It seems that you haven't accepted the invitation. Here is the link:
[https://github.com/Rahgooy/indep_num/invitations](https://github.com/Rahgooy/indep_num/invitations)

**Pull request merged**
