### PR TITLE
Victor dev

### PR DESCRIPTION
**Pull request by doogrammargood**
The caching helped a lot! 

I changed mutate_worst_vertex so that it chooses randomly among the vertices with a bias toward the worse ones rather than always choosing the worst vertex.

I also aggregated the calculation of `g.lovasz_theta()` with the calculation of the `g.vertex_cost_list`. Since we calculate one when we calculate the other in the process, it makes sense to cache as soon as we need either. Similarly for `g.independence_number()` and the list of independent sets.

There is still some inefficiency in the caching. Ideally, we should find that `independence_number_and_maximal_independent_sets` is called as often as `fit`- once per every new graph. I don't think this will help much, because most of the time is spent in calculating `lovasz_theta`, which is called as often as `fit` and so cannot be further optimized

My next questions are: 
-How should we go about removing items from the cache? I haven't tried it, but I expect the program will keep writing to the cache until it runs out of memory and crashes.
-What do we do if there is a hash collision in the cache?

### CODE REVIEW

**Comment by Rahgooy** [comment]
> How should we go about removing items from the cache? I haven't tried it, but I expect the program will keep writing to the cache until it runs out of memory and crashes.

I tried it with n<30 and it didn't crash. But, it is good if we could find a policy for removing items from the cache. For example, we could clear cache after each increment because we don't need the low order graphs anymore, right?

> What do we do if there is a hash collision in the cache?

Nothing. How do we know if there is a collision?

**Comment by doogrammargood** [comment]
We will need the values for the graphs one vertex smaller (in ), but we can get rid of graphs on n-2 vertices. We might also add a counter so that we can clear entries that are old enough.

I was confused about the hash- it seems that python's \_\_hash__() function [handles collisions automatically](https://stackoverflow.com/questions/9010222/how-can-python-dict-have-multiple-keys-with-same-hash)

**Comment by doogrammargood** [comment]
The strategy of mutating one vertex at a time performs pretty well, but then tends to plateau. I've been able to get very high fitness values (1.6/1.7ish), but at the cost of looking at big graphs (like 50 vertices).

I think the drawback of this method is that it reduces genetic diversity. Now, I am thinking that we should keep track of several graphs (a "vanguard"), apply genetic algorithms to each (without any crossover function), and prune the vanguard according to fitness.

**Comment by Rahgooy** [comment]
Isn't vanguard another name for elites?
But, I like the idea, maybe we could reduce the population size if we don't use cross-over. Also, having more iteration in each increment or maybe having dynamic iteration numbers. For example, linearly increasing the number of iterations after each increment to give bigger graphs more time to evolve.

**Comment by Rahgooy** [comment]
> I was confused about the hash- it seems that python's __hash__() function handles collisions automatically

@doogrammargood According to the link, the dictionary handles collisions, not __hash__(). It seems that the dictionary is a proper hash table which first uses the hash function to find a slot for the key, then if the slot is not empty compares the two keys and appends if they are not equal. 

For example in our case, let say `g1 = "1001001..."` and `g2="1001000..."` but they both have the same `hash = 1000`. Because we use hash values as keys then the dictionary will not detect the collision and overrides the value because `1000 == 1000`. But if we use the stringified adjacency matrix as keys then the dictionary will detect the collision `g1!=g2`. 

So, maybe it's better to do it in that way, no?

**Pull request merged**
